version: '3.1'
services:
  easyappointments:
    image: 'alextselegidis/easyappointments:latest'
    environment:
      - BASE_URL=http://localhost:8080
      - DEBUG_MODE=TRUE
      - DB_HOST=mysql
      - DB_NAME=easyappointments
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - '8080:80'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
